cmd_scripts/perl/Perf-Trace-Util/Context.o := gcc -Wp,-MD,scripts/perl/Perf-Trace-Util/.Context.o.d -Wp,-MT,scripts/perl/Perf-Trace-Util/Context.o -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -fno-strict-aliasing -DHAVE_ARCH_X86_64_SUPPORT -Iarch/x86/include/generated -DHAVE_SYSCALL_TABLE_SUPPORT -DHAVE_PERF_REGS_SUPPORT -DHAVE_ARCH_REGS_QUERY_REGISTER_OFFSET -O6 -fno-omit-frame-pointer -ggdb3 -funwind-tables -Wall -Wextra -std=gnu99 -fstack-protector-all -D_FORTIFY_SOURCE=2 -I/home/zbl/prepap/monitoring/linux/tools/perf/util/include -I/home/zbl/prepap/monitoring/linux/tools/perf/arch/x86/include -I/home/zbl/prepap/monitoring/linux/tools/include/uapi -I/home/zbl/prepap/monitoring/linux/tools/include/ -I/home/zbl/prepap/monitoring/linux/tools/arch/x86/include/uapi -I/home/zbl/prepap/monitoring/linux/tools/arch/x86/include/ -I/home/zbl/prepap/monitoring/linux/tools/arch/x86/ -I/home/zbl/prepap/monitoring/linux/tools/perf/util -I/home/zbl/prepap/monitoring/linux/tools/perf -I/home/zbl/prepap/monitoring/linux/tools/lib/ -I/usr/include/python2.7/ -I/home/zbl/temp/papi/src -I/home/zbl/temp/papi/src/testlib /home/zbl/temp/papi/src/testlib/do_loops.o /home/zbl/temp/papi/src/testlib/test_utils.o /home/zbl/temp/papi/src/testlib/dummy.o /home/zbl/temp/papi/src/libpapi.a -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DHAVE_SYNC_COMPARE_AND_SWAP_SUPPORT -DHAVE_PTHREAD_ATTR_SETAFFINITY_NP -DHAVE_PTHREAD_BARRIER -DHAVE_EVENTFD -DHAVE_GET_CURRENT_DIR_NAME -DHAVE_DWARF_GETLOCATIONS_SUPPORT -DHAVE_GLIBC_SUPPORT -DHAVE_AIO_SUPPORT -DHAVE_SCHED_GETCPU_SUPPORT -DHAVE_SETNS_SUPPORT -DHAVE_LIBELF_SUPPORT -DHAVE_LIBELF_MMAP_SUPPORT -DHAVE_ELF_GETPHDRNUM_SUPPORT -DHAVE_GELF_GETNOTE_SUPPORT -DHAVE_ELF_GETSHDRSTRNDX_SUPPORT -DHAVE_DWARF_SUPPORT -DHAVE_LIBBPF_SUPPORT -DHAVE_BPF_PROLOGUE -DHAVE_SDT_EVENT -DHAVE_JITDUMP -DHAVE_DWARF_UNWIND_SUPPORT -DNO_LIBUNWIND_DEBUG_FRAME -DHAVE_LIBUNWIND_SUPPORT -DHAVE_LIBCRYPTO_SUPPORT -I/usr/include/slang -DHAVE_SLANG_SUPPORT -DHAVE_GTK2_SUPPORT -DHAVE_LIBPERL_SUPPORT -DHAVE_TIMERFD_SUPPORT -DHAVE_LIBPYTHON_SUPPORT -DHAVE_CPLUS_DEMANGLE_SUPPORT -DHAVE_LIBBFD_SUPPORT -DHAVE_ZLIB_SUPPORT -DHAVE_LZMA_SUPPORT -DHAVE_BACKTRACE_SUPPORT -DHAVE_LIBNUMA_SUPPORT -DHAVE_KVM_STAT_SUPPORT -DHAVE_PERF_READ_VDSO32 -DHAVE_AUXTRACE_SUPPORT -D"BUILD_STR(s)=$(pound)s" -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib64/perl5/CORE -Wno-redundant-decls -Wno-strict-prototypes -Wno-unused-parameter -Wno-nested-externs -Wno-undef -Wno-switch-default -Wno-shadow -c -o scripts/perl/Perf-Trace-Util/Context.o scripts/perl/Perf-Trace-Util/Context.c

source_scripts/perl/Perf-Trace-Util/Context.o := scripts/perl/Perf-Trace-Util/Context.c

deps_scripts/perl/Perf-Trace-Util/Context.o := \
  /usr/include/stdc-predef.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdbool.h \
  /usr/lib64/perl5/CORE/EXTERN.h \
  /usr/lib64/perl5/CORE/perl.h \
  /usr/lib64/perl5/CORE/config.h \
  /usr/include/sys/types.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/time.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/bits/select2.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h \
  /usr/include/ctype.h \
  /usr/include/xlocale.h \
  /usr/include/locale.h \
  /usr/include/bits/locale.h \
  /usr/include/setjmp.h \
  /usr/include/bits/setjmp.h \
  /usr/include/bits/setjmp2.h \
  /usr/include/sys/param.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/bits/posix2_lim.h \
  /usr/include/bits/xopen_lim.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/signal.h \
  /usr/include/bits/signum.h \
  /usr/include/bits/siginfo.h \
  /usr/include/bits/sigaction.h \
  /usr/include/bits/sigcontext.h \
  /usr/include/bits/sigstack.h \
  /usr/include/sys/ucontext.h \
  /usr/include/bits/sigthread.h \
  /usr/include/bits/param.h \
  /usr/include/linux/param.h \
  /usr/include/asm/param.h \
  /usr/include/asm-generic/param.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/bits/stdlib.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/bits/unistd.h \
  /usr/include/sys/wait.h \
  /usr/include/string.h \
  /usr/include/bits/string.h \
  /usr/include/bits/string2.h \
  /usr/include/bits/string3.h \
  /usr/include/netinet/in.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/sys/socket.h \
  /usr/include/sys/uio.h \
  /usr/include/bits/uio.h \
  /usr/include/bits/socket.h \
  /usr/include/bits/socket_type.h \
  /usr/include/bits/sockaddr.h \
  /usr/include/asm/socket.h \
  /usr/include/asm-generic/socket.h \
  /usr/include/asm/sockios.h \
  /usr/include/asm-generic/sockios.h \
  /usr/include/bits/socket2.h \
  /usr/include/bits/in.h \
  /usr/include/arpa/inet.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/bits/timex.h \
  /usr/include/sys/time.h \
  /usr/include/sys/times.h \
  /usr/include/errno.h \
  /usr/include/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/../../arch/x86/include/uapi/asm/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/errno-base.h \
  /usr/include/netdb.h \
  /usr/include/rpc/netdb.h \
  /usr/include/bits/netdb.h \
  /usr/include/sys/ioctl.h \
  /usr/include/bits/ioctls.h \
  /usr/include/asm/ioctls.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/ioctls.h \
  /usr/include/linux/ioctl.h \
  /usr/include/asm/ioctl.h \
  /usr/include/asm-generic/ioctl.h \
  /usr/include/bits/ioctl-types.h \
  /usr/include/sys/ttydefaults.h \
  /usr/include/dirent.h \
  /usr/include/bits/dirent.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/float.h \
  /usr/lib64/perl5/CORE/handy.h \
  /usr/include/inttypes.h \
  /usr/lib64/perl5/CORE/unixish.h \
  /usr/include/pthread.h \
  /usr/include/sched.h \
  /usr/include/bits/sched.h \
  /usr/lib64/perl5/CORE/iperlsys.h \
  /usr/lib64/perl5/CORE/perlio.h \
  /usr/include/stdio.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/bits/stdio.h \
  /usr/include/bits/stdio2.h \
  /usr/lib64/perl5/CORE/perly.h \
  /usr/lib64/perl5/CORE/sv.h \
  /usr/lib64/perl5/CORE/regexp.h \
  /usr/lib64/perl5/CORE/op_reg_common.h \
  /usr/lib64/perl5/CORE/util.h \
  /usr/lib64/perl5/CORE/form.h \
  /usr/lib64/perl5/CORE/gv.h \
  /usr/lib64/perl5/CORE/pad.h \
  /usr/lib64/perl5/CORE/cv.h \
  /usr/lib64/perl5/CORE/opnames.h \
  /usr/lib64/perl5/CORE/op.h \
  /usr/lib64/perl5/CORE/reentr.h \
  /usr/include/pwd.h \
  /usr/include/grp.h \
  /usr/include/crypt.h \
  /usr/include/shadow.h \
  /usr/include/paths.h \
  /usr/lib64/perl5/CORE/hv.h \
  /usr/lib64/perl5/CORE/cop.h \
  /usr/lib64/perl5/CORE/mydtrace.h \
  /usr/lib64/perl5/CORE/av.h \
  /usr/lib64/perl5/CORE/mg.h \
  /usr/lib64/perl5/CORE/scope.h \
  /usr/lib64/perl5/CORE/warnings.h \
  /usr/lib64/perl5/CORE/utf8.h \
  /usr/lib64/perl5/CORE/parser.h \
  /usr/include/math.h \
  /usr/include/bits/huge_val.h \
  /usr/include/bits/huge_valf.h \
  /usr/include/bits/huge_vall.h \
  /usr/include/bits/inf.h \
  /usr/include/bits/nan.h \
  /usr/include/bits/mathdef.h \
  /usr/include/bits/mathcalls.h \
  /usr/include/bits/mathinline.h \
  /usr/lib64/perl5/CORE/patchlevel.h \
  /usr/lib64/perl5/CORE/intrpvar.h \
  /usr/lib64/perl5/CORE/thread.h \
  /usr/lib64/perl5/CORE/pp.h \
  /usr/lib64/perl5/CORE/proto.h \
  /usr/lib64/perl5/CORE/opcode.h \
  /usr/lib64/perl5/CORE/embedvar.h \
  /usr/lib64/perl5/CORE/embed.h \
  /usr/lib64/perl5/CORE/perlvars.h \
  /usr/lib64/perl5/CORE/mg_vtable.h \
  /usr/lib64/perl5/CORE/overload.h \
  /usr/include/sys/ipc.h \
  /usr/include/bits/ipctypes.h \
  /usr/include/bits/ipc.h \
  /usr/include/sys/sem.h \
  /usr/include/bits/sem.h \
  /usr/include/sys/file.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/linux/falloc.h \
  /usr/include/bits/fcntl2.h \
  /usr/lib64/perl5/CORE/XSUB.h \
  /usr/lib64/perl5/CORE/perlapi.h \
  scripts/perl/Perf-Trace-Util/../../../perf.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/types.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm/bitsperlong.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/../../arch/x86/include/uapi/asm/bitsperlong.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/linux/stddef.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/linux/perf_event.h \
  /usr/include/asm/byteorder.h \
  /usr/include/linux/byteorder/little_endian.h \
  /usr/include/linux/swab.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/include/asm/swab.h \
  scripts/perl/Perf-Trace-Util/../../../perf-sys.h \
  /usr/include/sys/syscall.h \
  /home/zbl/prepap/monitoring/linux/tools/arch/x86/include/uapi/asm/unistd.h \
  /home/zbl/prepap/monitoring/linux/tools/arch/x86/include/asm/unistd_64.h \
  /usr/include/bits/syscall.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/compiler.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/compiler-gcc.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm/barrier.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm/../../arch/x86/include/asm/barrier.h \
  scripts/perl/Perf-Trace-Util/../../../util/target.h \
  scripts/perl/Perf-Trace-Util/../../../util/trace-event.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/traceevent/event-parse.h \
  /usr/include/regex.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/traceevent/trace-seq.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/traceevent/trace-seq.h \
  scripts/perl/Perf-Trace-Util/../../../util/parse-events.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/list.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/poison.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /usr/include/byteswap.h \

scripts/perl/Perf-Trace-Util/Context.o: $(deps_scripts/perl/Perf-Trace-Util/Context.o)

$(deps_scripts/perl/Perf-Trace-Util/Context.o):
