cmd_builtin-trace.o := gcc -Wp,-MD,./.builtin-trace.o.d -Wp,-MT,builtin-trace.o -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -fno-strict-aliasing -DHAVE_ARCH_X86_64_SUPPORT -Iarch/x86/include/generated -DHAVE_SYSCALL_TABLE_SUPPORT -DHAVE_PERF_REGS_SUPPORT -DHAVE_ARCH_REGS_QUERY_REGISTER_OFFSET -O6 -fno-omit-frame-pointer -ggdb3 -funwind-tables -Wall -Wextra -std=gnu99 -fstack-protector-all -D_FORTIFY_SOURCE=2 -I/home/zbl/prepap/monitoring/linux/tools/perf/util/include -I/home/zbl/prepap/monitoring/linux/tools/perf/arch/x86/include -I/home/zbl/prepap/monitoring/linux/tools/include/uapi -I/home/zbl/prepap/monitoring/linux/tools/include/ -I/home/zbl/prepap/monitoring/linux/tools/arch/x86/include/uapi -I/home/zbl/prepap/monitoring/linux/tools/arch/x86/include/ -I/home/zbl/prepap/monitoring/linux/tools/arch/x86/ -I/home/zbl/prepap/monitoring/linux/tools/perf/util -I/home/zbl/prepap/monitoring/linux/tools/perf -I/home/zbl/prepap/monitoring/linux/tools/lib/ -I/usr/include/python2.7/ -I/home/zbl/temp/papi/src -I/home/zbl/temp/papi/src/testlib /home/zbl/temp/papi/src/testlib/do_loops.o /home/zbl/temp/papi/src/testlib/test_utils.o /home/zbl/temp/papi/src/testlib/dummy.o /home/zbl/temp/papi/src/libpapi.a -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DHAVE_SYNC_COMPARE_AND_SWAP_SUPPORT -DHAVE_PTHREAD_ATTR_SETAFFINITY_NP -DHAVE_PTHREAD_BARRIER -DHAVE_EVENTFD -DHAVE_GET_CURRENT_DIR_NAME -DHAVE_DWARF_GETLOCATIONS_SUPPORT -DHAVE_GLIBC_SUPPORT -DHAVE_AIO_SUPPORT -DHAVE_SCHED_GETCPU_SUPPORT -DHAVE_SETNS_SUPPORT -DHAVE_LIBELF_SUPPORT -DHAVE_LIBELF_MMAP_SUPPORT -DHAVE_ELF_GETPHDRNUM_SUPPORT -DHAVE_GELF_GETNOTE_SUPPORT -DHAVE_ELF_GETSHDRSTRNDX_SUPPORT -DHAVE_DWARF_SUPPORT -DHAVE_LIBBPF_SUPPORT -DHAVE_BPF_PROLOGUE -DHAVE_SDT_EVENT -DHAVE_JITDUMP -DHAVE_DWARF_UNWIND_SUPPORT -DNO_LIBUNWIND_DEBUG_FRAME -DHAVE_LIBUNWIND_SUPPORT -DHAVE_LIBCRYPTO_SUPPORT -I/usr/include/slang -DHAVE_SLANG_SUPPORT -DHAVE_GTK2_SUPPORT -DHAVE_LIBPERL_SUPPORT -DHAVE_TIMERFD_SUPPORT -DHAVE_LIBPYTHON_SUPPORT -DHAVE_CPLUS_DEMANGLE_SUPPORT -DHAVE_LIBBFD_SUPPORT -DHAVE_ZLIB_SUPPORT -DHAVE_LZMA_SUPPORT -DHAVE_BACKTRACE_SUPPORT -DHAVE_LIBNUMA_SUPPORT -DHAVE_KVM_STAT_SUPPORT -DHAVE_PERF_READ_VDSO32 -DHAVE_AUXTRACE_SUPPORT -D"BUILD_STR(s)=$(pound)s" -DSTRACE_GROUPS_DIR="BUILD_STR(share/perf-core/strace/groups)" -c -o builtin-trace.o builtin-trace.c

source_builtin-trace.o := builtin-trace.c

deps_builtin-trace.o := \
  /usr/include/stdc-predef.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/traceevent/event-parse.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdbool.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h \
  /usr/include/stdio.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/wchar.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/bits/stdio.h \
  /usr/include/bits/stdio2.h \
  /usr/include/regex.h \
  /usr/include/sys/types.h \
  /usr/include/time.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/byteswap-16.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/sigset.h \
  /usr/include/bits/time.h \
  /usr/include/bits/select2.h \
  /usr/include/sys/sysmacros.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/string.h \
  /usr/include/xlocale.h \
  /usr/include/bits/string.h \
  /usr/include/bits/string2.h \
  /usr/include/stdlib.h \
  /usr/include/bits/string3.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/traceevent/trace-seq.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/api/fs/tracing_path.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm/bitsperlong.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/../../arch/x86/include/uapi/asm/bitsperlong.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/dirent.h \
  /usr/include/bits/dirent.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/bpf/bpf.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/linux/bpf.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/linux/bpf_common.h \
  util/bpf_map.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/compiler.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/compiler-gcc.h \
  builtin.h \
  util/util.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/bits/uio.h \
  /usr/include/linux/falloc.h \
  /usr/include/bits/stat.h \
  /usr/include/bits/fcntl2.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/bits/stdlib.h \
  util/cgroup.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/refcount.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/atomic.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm/atomic.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm/../../arch/x86/include/asm/atomic.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm/../../arch/x86/include/asm/rmwcc.h \
  /home/zbl/prepap/monitoring/linux/tools/arch/x86/include/asm/cmpxchg.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /usr/include/byteswap.h \
  util/color.h \
  util/config.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/list.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/poison.h \
  util/debug.h \
  util/event.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h \
  /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/bits/posix2_lim.h \
  /usr/include/bits/xopen_lim.h \
  util/../perf.h \
  /usr/include/bits/timex.h \
  /usr/include/linux/stddef.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/linux/perf_event.h \
  /usr/include/linux/ioctl.h \
  /usr/include/asm/ioctl.h \
  /usr/include/asm-generic/ioctl.h \
  /usr/include/asm/byteorder.h \
  /usr/include/linux/byteorder/little_endian.h \
  /usr/include/linux/swab.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/include/asm/swab.h \
  util/../perf-sys.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/bits/unistd.h \
  /usr/include/sys/syscall.h \
  /home/zbl/prepap/monitoring/linux/tools/arch/x86/include/uapi/asm/unistd.h \
  /home/zbl/prepap/monitoring/linux/tools/arch/x86/include/asm/unistd_64.h \
  /usr/include/bits/syscall.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm/barrier.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm/../../arch/x86/include/asm/barrier.h \
  util/../util/target.h \
  util/build-id.h \
  util/tool.h \
  util/perf_regs.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/arch/x86/include/perf_regs.h \
  /home/zbl/prepap/monitoring/linux/tools/arch/x86/include/uapi/asm/perf_regs.h \
  util/../ui/helpline.h \
  util/../ui/../util/cache.h \
  util/../ui/../util/strbuf.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/subcmd/pager.h \
  util/../ui/../util/../ui/ui.h \
  /usr/include/pthread.h \
  /usr/include/sched.h \
  /usr/include/bits/sched.h \
  /usr/include/bits/setjmp.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/string.h \
  util/../ui/progress.h \
  util/../ui/util.h \
  util/env.h \
  util/cpumap.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/perf.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/debug.h \
  util/event.h \
  util/evlist.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/api/fd/array.h \
  util/evsel.h \
  util/xyarray.h \
  util/symbol_conf.h \
  util/counts.h \
  util/mmap.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/ring_buffer.h \
  /usr/include/aio.h \
  /usr/include/bits/siginfo.h \
  util/auxtrace.h \
  /usr/include/errno.h \
  /usr/include/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/../../arch/x86/include/uapi/asm/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/errno.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/errno-base.h \
  util/session.h \
  util/trace-event.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/traceevent/trace-seq.h \
  util/parse-events.h \
  util/header.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/bitmap.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/bitops.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/bits.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/__ffs.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/__ffz.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/fls.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/__fls.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/fls64.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/find.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/hweight.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/const_hweight.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/atomic.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/bitops/non-atomic.h \
  util/env.h \
  util/pmu.h \
  util/machine.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/rbtree.h \
  util/map_groups.h \
  util/rwsem.h \
  util/dso.h \
  util/data.h \
  util/ordered-events.h \
  util/debug.h \
  util/util.h \
  /usr/include/signal.h \
  /usr/include/bits/signum.h \
  /usr/include/bits/sigaction.h \
  /usr/include/bits/sigcontext.h \
  /usr/include/bits/sigstack.h \
  /usr/include/sys/ucontext.h \
  /usr/include/bits/sigthread.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/subcmd/exec-cmd.h \
  util/machine.h \
  util/map.h \
  util/symbol.h \
  util/map_symbol.h \
  util/branch.h \
  util/path.h \
  /usr/include/libelf.h \
  /usr/include/elf.h \
  /usr/include/gelf.h \
  util/path.h \
  util/session.h \
  util/thread.h \
  util/srccode.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/strlist.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/rblist.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/intlist.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/subcmd/parse-options.h \
  util/strlist.h \
  util/intlist.h \
  util/thread_map.h \
  util/stat.h \
  /usr/include/sys/time.h \
  /usr/include/sys/resource.h \
  /usr/include/bits/resource.h \
  /usr/include/sys/wait.h \
  util/rblist.h \
  trace/beauty/beauty.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/trace-event.h \
  util/parse-events.h \
  util/bpf-loader.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/err.h \
  /home/zbl/prepap/monitoring/linux/tools/lib/bpf/libbpf.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/callchain.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/event.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/map_symbol.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/branch.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/print_binary.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/string2.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/syscalltbl.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/rb_resort.h \
  /usr/include/inttypes.h \
  /usr/include/poll.h \
  /usr/include/sys/poll.h \
  /usr/include/bits/poll.h \
  /usr/include/bits/poll2.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/filter.h \
  /usr/include/linux/random.h \
  /usr/include/linux/irqnr.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/stringify.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/time64.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/util/sane_ctype.h \
  trace/beauty/arch_errno_names.c \
  /home/zbl/prepap/monitoring/linux/tools/perf/trace/beauty/generated/arch_errno_name_array.c \
  trace/beauty/eventfd.c \
  trace/beauty/futex_op.c \
  /usr/include/linux/futex.h \
  trace/beauty/futex_val3.c \
  trace/beauty/mmap.c \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/linux/mman.h \
  /home/zbl/prepap/monitoring/linux/tools/arch/x86/include/uapi/asm/mman.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/mman.h \
  /home/zbl/prepap/monitoring/linux/tools/include/uapi/asm-generic/mman-common.h \
  /home/zbl/prepap/monitoring/linux/tools/include/asm-generic/hugetlb_encode.h \
  /home/zbl/prepap/monitoring/linux/tools/include/linux/log2.h \
  /home/zbl/prepap/monitoring/linux/tools/perf/trace/beauty/generated/mmap_flags_array.c \
  /home/zbl/prepap/monitoring/linux/tools/perf/trace/beauty/generated/madvise_behavior_array.c \
  trace/beauty/mode_t.c \
  /usr/include/sys/stat.h \
  trace/beauty/msg_flags.c \
  /usr/include/sys/socket.h \
  /usr/include/sys/uio.h \
  /usr/include/bits/socket.h \
  /usr/include/bits/socket_type.h \
  /usr/include/bits/sockaddr.h \
  /usr/include/asm/socket.h \
  /usr/include/asm-generic/socket.h \
  /usr/include/asm/sockios.h \
  /usr/include/asm-generic/sockios.h \
  /usr/include/bits/socket2.h \
  trace/beauty/open_flags.c \
  trace/beauty/perf_event_open.c \
  trace/beauty/pid.c \
  trace/beauty/sched_policy.c \
  trace/beauty/seccomp.c \
  trace/beauty/signum.c \
  trace/beauty/socket_type.c \
  trace/beauty/waitid_options.c \

builtin-trace.o: $(deps_builtin-trace.o)

$(deps_builtin-trace.o):
